### ISSUE TITLE
regioned-solid not returning anything

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#105]
Can't replicate my issue. I have a merged-solid with 18 regions, however the regioned-solid that I build is empty. Looking into the source code, the filled-regions test returns nil. But I can't see which region is not filled / don't get feedback... Tried to replicate with code below, but this (Murphy's law) works. You can use this as example code for your object, because it's a pity that YADD lack any form of example for the regioned-solid object.

```lisp
(define-object regioned-solid sample (base-object)
  :objects
  ((box-sequence :type 'box-solid :sequence (:size 4) :width 3 :length 3 :height 3 
		 :display-controls (list :color :red)
		 :center (if (the-child :first?) (the center)
			     (translate (the-child :previous :center) :up 1 :right 1 :rear 1)))
   (merge :type 'merged-solid :other-brep (list-elements (the box-sequence)))
   (regions :type 'regioned-solid :brep (the merge))
   )
  )

**Comment by genworks** [comment]
Moved to internal tracking list.
