### ISSUE TITLE
base face of an extruded solid enlarged: feature or bug?

### ISSUE THREAD

**Issue by tobievandenberg** [genworks/gendl#110]
Constructing an extruded-solid from a square profile, a solid is obtained. The base and top face of this solid are larger than the surface closed in by the profile however. Is there a reason for this of is it a bug?

(in-package :gdl-user)
(define-object offset-surface-issue (base-object)
  :input-slots
  (
   (size 1.0 :settable)
   (distance 0.5 :settable)
   (vector #(0.3 0.3 1.0) :settable)
   (offset-distance 0.2 :settable)
   )
  :objects
  ( 
(profile
    :type 'b-spline-curve
    :degree 1
    :control-points (list #(0.0 0.0 0.0) 
			  (make-point 0.0 (the size) 0.0)
			  (make-point (the size) (the size) 0.0)
			  (make-point (the size) 0.0 0.0)
			  #(0.0 0.0 0.0)))

  (extrusion
   :type 'extruded-solid
   :profile (the profile)
   :distance (the distance)
   :axis-vector (the vector)
   :display-controls (list :color :blue :transparency 0.5))

(faces
    :type 'surface
    :sequence (:size (length (list-elements (the extrusion faces))))
    :built-from (the extrusion (faces (the-child index)))
    :display-controls (list :color :red :transparency 0.5))

   (face-breps
    :type 'transformed-solid
    :sequence (:size (length (list-elements (the extrusion face-breps))))
    :brep (the extrusion (face-breps (the-child index)))
    :display-controls (list :color :green :transparency 0.5))
    ))

**Comment by genworks** [comment]
Moved to internal tracking list.
