### ISSUE TITLE
offset-point-along should warn

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#155]
Unlike other methods, the offset-point-along doesn't warn if the distance is bigger than the distance of the curve and without user notice return the end point of the curve. The "point" method on a curve does warn about this and pins u-values to u-extremes. Shouldn't the offset-point-along method do something similar? In my case, it could have helped to find an error in my code.

```lisp
(define-object offset-test (base-object)

  :computed-slots
  ((correct (the my-curve (offset-point-along 0 5)))
   (correct-pt (get-3d-point-of (the correct)))
   (should-warn (the my-curve (offset-point-along 0 100)))
   (should-warn-pt (get-3d-point-of (the should-warn)))
   )
  
  :objects
  ((my-curve :type 'fitted-curve :points (list (the center) 
					      (translate (the center) :rear 5 :right 5)
					      (translate (the center) :right 10)))))
```

**Comment by genworks** [comment]
Moving to internal tracking list.
