### ISSUE TITLE
VRML scene redraw on geometry click

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#164]
When visualizing geometry in VRML format through BS Contact plugin: any click on geometry, including right-clicks, lead to complete regeneration of VRML scene.

**Comment by genworks** [comment]
Opening this up for submission. $200-300

Notes: VRML output should be deprecated and removed from tasty/ta2 etc. 

This behavior should be checked and fixed if necessary for X3D and X3DOM output in ta2 and tasty. GDL should standardize on these two output formats, clean them up, verify, document them, and retire VRML format.

**Comment by genworks** [comment]
vrml deprecated, closing this.
