### ISSUE TITLE
uv-curve not correct

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#170]
Given the iwp file attached in separate e-mail (can't upload in this message dialog), take out the brep and visualize if you need to. Take ``(edges 2)`` or the middle airfoil, confirm that it's on 2 faces, and demand the ``uv-curve`` on the first face. Now observe that the curve has a very weird progression in uv-space and start+end points are overlapping, which is impossible. Can you replicate this case and give feedback ASAP, because this is halting a student's graduation work. Thanks.

```lisp
(make-self 'native-reader :file-name "some/path")
(setq brep (the (breps 0)))
(setq crv (the-object brep (edges 2) (uv-curve (the-object brep (faces 0)))))
(the-object crv :start)
(the-object crv :end)
```

**Comment by genworks** [comment]
Moved to internal tracking list, following up with reporter by email.
