### ISSUE TITLE
Tasty svg line-thickness

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#173]
The first time an SVG image is drawn, all lines in the wireframe drawing have a certain line-thickness. When the user hovers over it, the line is correctly highlighted, but changes line-thickness afterwards. Replicate by opening the ``robot:assembly`` in Tasty, draw all nodes in SVG mode. Then note the thickness of all lines, then hover over one, move cursor away from line, and note thickness change.

**Comment by genworks** [comment]
What version of GDL/Gendl is this happening in? I believe this issue has been fixed some time ago and should not be there in current codebase or in released 1588. Unless I'm looking at something different.

**Comment by reiniervandijk** [comment]
This is 1587p001.

**Comment by genworks** [comment]
Closing as already fixed in current version.
