### ISSUE TITLE
volume of box-solid always :unbound

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#51]
Object surf:box-solid inherits both surf:brep and geom-base:box. Object geom-base:box defines volume as multiplication of width, length, height. Object surf:brep defines it as the result of a geometry kernel function call. Unfortunately the slot-status of :volume is now always set to :unbound, no matter if volume was already evaluated or not. This is in absolute contrast to lean computing on the basis of dependency tracking. Suggestion to keep volume message definition according to box and remove brep definition.

```lisp
gdl-user> (make-self 'box-solid :width 2 :length 3 :height 4)
#<box-solid @ #x26ccd92a>
gdl-user> (the (slot-status :volume))
:unbound
gdl-user> (the volume)
24.000000000000007
gdl-user> (the (slot-status :volume))
:unbound

**Comment by genworks** [comment]
Indeed maybe we can override the volume for this specific brep and just compute it directly as we do for box...

**Comment by genworks** [comment]
moving to internal tracking list.
