### ISSUE TITLE
recursive behavior in trimmed-surface face's face's face

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#73]
It this logical? the trimmed-surface is a face. It's basis-surface is obviously potentially bigger that the trimmed region. However, the brep of the object has another face, this face on it's turn has a basis-surface. But, that one is exactly the same. And so we can go on to the next brep in the tree and again and again. Is this behavior as marketed?

**Comment by genworks** [comment]
Moved to internal tracking list.
