### ISSUE TITLE
[experimental] assembly-import misses object names

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#80]
When importing a step file, names for points and curves are properly extracted. However, names for breps (i.e. advanced-faces / open-shells in STEP) are not captured. Is this hard-coded on Gendl side or is it the SMLib reader that doesn’t extract that info?

It would be quite nice to have the breps names showing up properly, because I need that level of semantics to select the correct objects in a tree.

**Comment by genworks** [comment]
moved to internal tracking list.
