### ISSUE TITLE
list-of-numbers influenced by tolerances

### ISSUE THREAD

**Issue by reiniervandijk** [genworks/gendl#95]
The current implementation of list-of-numbers is naive and leads to several complications. Consider:

```lisp
(setq u1 8.875776655249117e-4)
(setq u2 3.7043572627844927)
(setq lst (list-of-numbers u1 u2 (/ (- u2 u1) (1- 100))))
```

Now you would assume the list-of-numbers to have a length of 100, since I defined the step size like that. However:

```lisp
> (length lst)
99
```

This is due to tolerances, I understand. However, now consider the function equi-spaced-points in the curve object. You provide a number of points, say 100. Since the internal code uses the aforementioned method to calculate all (assumingly) 100 parametric values in the range of u1 - u2, it actually returns 99 points. This gave me errors, because I anticipated the same number of points that I've asked for.

Looking at body of list-of-numbers, erroneous line is:

```lisp
(dotimes (i (1+ (floor (/ (- num2 num1) increment)))  ...
```

Because this gives:
```lisp
> (/ (- u2 u1) (/ (- u2 u1) (1- 100)))
98.99999999999999
```

Documentation of list-of-numbers says: "Returns a list of incrementing numbers starting from 
num1 and ending with num2, inclusive." That's actually not true, as shown.

**Comment by reiniervandijk** [comment]
This fix is now pending for almost two years and has manifested itself again in student code while working with the MMG. Is this issue representative indicative for the speed with which user-contributions are merged into the language? If so, we, TUD, will manage our own set of fixes to the language that we will circulate among students.

**Comment by reiniervandijk** [comment]
Another contribution to the language (name of the function can be subject to change):

```lisp
(defun list-of-n-numbers (num1 num2 n)
  "returns a list of n numbers between bounds num1 and num2. Bounds are inclusive"
  (let ((increment (/ (- num2 num1) (- n 1)))
	(result-list nil))
    (dotimes (i (- n 1) (nreverse (cons num2 result-list)))
      (push (+ num1 (* i increment)) result-list))))
```

**Comment by genworks** [comment]
The fixes will be rolled into next major release, slated for January 2016, including clear release notes. This will not be included in an interim patch, due to risk of breaking existing code (even though the current function indeed can produce incorrect results, some production applications may be depending on these results).  

Indeed, applications which require the fixed behavior can and should carry the code for the fix locally, which code can be retired when it moves to the next major release which includes the fix.

**Comment by genworks** [comment]
The issue will be closed when it is committed into current development work-in-progress. Work-in-progress builds are also expected to be made available between now and January 2016.

**Comment by genworks** [comment]
updated list-of-numbers and list-of-n-numbers have been rolled into current "devo" branch.
